### ISSUE TITLE
Beneficiaries list does not refresh after beneficiary update

### ISSUE THREAD

**Issue by ldellisola** [Mamis-Solidarias/Frontend#110]

**Comment by isampedro** [comment]
Supposedly, it waits for the beneficiary to be updated before going back to the main view, where it refetches the data
![image](https://user-images.githubusercontent.com/42911632/198937726-738df6c1-aa91-4746-89f6-358fa836d988.png)
![image](https://user-images.githubusercontent.com/42911632/198937778-023eced1-5a39-43ac-a3ed-20a5c46cbf3f.png)
I think it's the same problem that happens in Campaigns
